#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_assignments)]
#![allow(unused_doc_comments)]
#![allow(unused_imports)]
use std::io::{self,Read,Write,BufReader,BufRead};
use std::fs::File;
use std::io::prelude::*;
use std::path::Path;
use crate::Grammar;

// auto-generate abstract syntax

// prepare Grammar - after parse_grammar first creates grammar
impl Grammar
{
   fn prepare(&mut self) -> String
   {
     let mut ASTS = String::new();
     let ltopt = if self.lifetime.len()>0 {format!("<{}>",&self.lifetime)}
          else {String::new()};
     // self.Rulesfor hashmap from nonterminals to set of usize indices

     // construct type of ast for each non-terminal NT
     let mut ntcx=self.Symbols.len()+1;  // separate from typedterminals
     let unithash = self.enumhash.get("()"); // semi-hack, default absyn
     if let Some(0) = unithash {
       self.enumhash.insert("()".to_owned(),ntcx);
       ntcx += 1;
     }
     for NT in self.Rulesfor.keys()  // for each non-terminal
     {
        let nti = *self.Symhash.get(NT).unwrap();
	if self.Symbols[nti].rusttype.len()<3 { // can override!
	  self.Symbols[nti].rusttype = format!("{}{}",NT,&ltopt);
	}
	if NT==&self.topsym {
          self.enumhash.insert(self.Symbols[nti].rusttype.clone(), 0);
	}
        else { // not topsym
	  self.enumhash.insert(self.Symbols[nti].rusttype.clone(), ntcx);
          ntcx += 1;
	}
     }//for each NT in grammar as keys of self.Rulesfor
     for (NT,NTrules) in self.Rulesfor.iter()
     {
        let nti = *self.Symhash.get(NT).unwrap();
        let ntsym = &self.Symbols[nti];
	ASTS.push_str(&format!("pub enum {} {{\n",&ntsym.rusttype));
	for ri in NTrules  // for each rule with NU on lhs
	{
	  self.Rules[*ri].lhs.rusttype = self.Symbols[nti].rusttype.clone();
	  // look at rhs of rule to form enum variant + action of each rule
	  if self.Rules[*ri].lhs.label.len()<1 {
	     self.Rules[*ri].lhs.label = format!("{}_{}",NT,ri);
	  }
	  let mut ACTION = format!("{}::{}",NT,&self.Rules[*ri].lhs.label);
	  let mut enumvar = format!("  {}",&self.Rules[*ri].lhs.label);
	  if self.Rules[*ri].rhs.len()>0 {
	    enumvar.push('(');
	    ACTION.push('(');
	  }
	  let mut rhsi = 0; // right-side index
	  for rsym in self.Rules[*ri].rhs.iter_mut()
	  {
	    let rsymi = *self.Symhash.get(&rsym.sym).unwrap(); //symbol index
	    let itemlabel = if rsym.label.len()>0 {rsym.label.clone()} else
            	            {format!("_item{}_",&rhsi)};
	    if !self.Symbols[rsymi].terminal {
	       rsym.rusttype = self.Symbols[rsymi].rusttype.clone();
	       enumvar.push_str(&format!("LBox<{}>,",&rsym.rusttype));
	       ACTION.push_str(&format!("parser.lbx({},{}),",&rhsi, &itemlabel));
	    }
	    else if &self.Symbols[rsymi].rusttype!="()" {
	      //rsym.rusttype = self.Symbols[rsymi].rusttype.clone();
	      enumvar.push_str(&format!("{},",&rsym.rusttype));
	      ACTION.push_str(&format!("{},",&itemlabel));
	    }
	    rhsi += 1;
	  }// for each symbol on rhs of rule ri
          if enumvar.ends_with(',') {
	      enumvar.pop(); 
	      enumvar.push(')');
	      ACTION.pop();
	      ACTION.push(')');
	  } else if enumvar.ends_with('(') {
	    enumvar.pop();
	    ACTION.pop();
	  }
	  ASTS.push_str(&enumvar); ASTS.push_str(",\n");
	  ACTION.push_str(" }");
	  if self.Rules[*ri].action.len()<=1 {
  	    self.Rules[*ri].action = ACTION;
	  }
//println!("Action for rule {}: {}",ri,&self.Rules[*ri].action);
	}// for each rule ri of non-terminal NT
	ASTS.push_str(&format!("  {}_Nothing,\n}}\n",NT));
	ASTS.push_str(&format!("impl{} Default for {} {{ fn default()->Self {{ {}::{}_Nothing }} }}\n\n",&ltopt,&ntsym.rusttype,NT,NT));
     }//for each non-terminal and set of rules

     // set Absyntype
     let topi = self.Symhash.get(&self.topsym).unwrap(); // must exist
     self.Absyntype = self.Symbols[*topi].rusttype.clone();
//println!("\n AST generated:\n\n{}",&ASTS);

     // add the grammar .extras
     self.Extras.push_str("use rustlr::LBox;\n");
     self.Extras.push_str(&format!("use crate::{}_ast;\n",&self.name));
     self.Extras.push_str(&format!("use crate::{}_ast::*;\n",&self.name));     
     ASTS
   }//prepare_gram


   pub fn writeabsyn(&mut self) ->Result<(),std::io::Error>
   {
     let ASTS = self.prepare();
     let filename = format!("{}_ast.rs",&self.name);
     let mut fd = File::create(&filename)?;
     write!(fd,"//Abstract syntax types generated by rustlr for grammar {}",&self.name)?;
     write!(fd,"\n    
#![allow(unused_variables)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(dead_code)]
extern crate rustlr;
use rustlr::LBox;\n\n")?;
     write!(fd,"{}",&ASTS)?;
     println!("Abstract syntax structures created in {}",&filename);
     Ok(())
   }//writeabsyn

}//impl Grammar
